### ISSUE TITLE
Feature request: Add Monolog format

### ISSUE THREAD

**Issue by nelson6e65** [mrodalgaard/language-log#11]
Should be nice add support for monolog (https://github.com/Seldaek/monolog) formats and json syntax.

**Comment by mrodalgaard** [comment]
Great, though I have never used it before.

Can you link to some example log files and possibly a log format description. All I can find is about the log levels [HERE](https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#log-levels) and that they are in accordance with the syslog protocol (RFC5424).

**Comment by jwhulette** [comment]
I found this, https://techzone.ergon.ch/syslog-message-format if it helps.
