### ISSUE TITLE
Files above 10,000 lines does not get grammar applied according to Atom.

### ISSUE THREAD

**Issue by LexHsu** [mrodalgaard/language-log#17]
great package! but why file above 10000 lines does not get grammer, can i set a bigger value, such as 30000?

**Comment by LexHsu** [comment]
and i use the package to filter android log, i found its slower when i press the filter button such as i, v, etc. how to make it faster?

**Comment by mrodalgaard** [comment]
I saw the 10,000 line limitation on older versions of Atom, but they might have changed it. It is an Atom internal. I do not think there is a way to change it.

See #14 for the unfortunate slow filtering behaviour. Although I have not found a solution yet.
