### ISSUE TITLE
Logformat changed for Android Marshmallow

### ISSUE THREAD

**Issue by coffee-with-milk** [mrodalgaard/language-log#24]
The output format of logcat has changed with Android Marshmallow. It would be great if this plugin supports the new output format.

```
# Example output on Marshmellow:
#    10-13 07:28:57.654  2814  2828 I TestRunner: 	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
#    10-13 07:28:57.654  2814  2828 I TestRunner: 	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
#    10-13 07:28:57.654  2814  2828 I TestRunner: 	at org.junit.runners.Suite.<init>(Suite.java:81)
#    |                   |     |    | |           |
#    |                   |     |    | tag         message
#    |                   |     |    |
#    timestamp           x1    x2   tagtype
```
compare with the output of "Pre-Marshmallow":
```
# Example message:
#      I/System.out( 4630): Some message
#      | |           |      |
#      | tag         |      message
#      |             |
#      tagtype       owner
```

See https://github.com/JakeWharton/pidcat/issues/102 for some inspiration.

**Comment by mrodalgaard** [comment]
Looks pretty good to me. I might add the last parentheses, that indicates where the output was from. But that part was also present in the old format. Which syntaxes are you missing?

<img width="1199" alt="screen shot 2017-01-15 at 20 48 26" src="https://cloud.githubusercontent.com/assets/659763/21965623/0a7d11ee-db64-11e6-80e8-cb2abb3b1ced.png">

**Comment by coffee-with-milk** [comment]
Thanks for looking into this issue. I was missing the first mentioned syntax, but it seems to be fixed by now. Don't know whether it was your commit or the atom changes. Thank you!
