### ISSUE TITLE
Opening log file crashes tree view colors of changed files

### ISSUE THREAD

**Issue by Irthen** [mrodalgaard/language-log#27]
Hi :),

at first: I love this package because it fits nicely into my tool chain, so I am able to stay at atom watching the log file gets filled up with debug information. No need anymore to switch to terminal!

Unfortunately, the colors of changes files in the tree view crashes if the log file gets opened by terminal command "atom -a path/to/log".

Do you need more information about this? Maybe you are able to reproduce this bug on yourself.

Thanks & cheers,
Flo

**Comment by mrodalgaard** [comment]
Hi, I'm not sure I understand what _'...the colors of changes files in the tree view..._ means. Could you add a screenshot that shows this. If something crashes, Atom normally presents to you a dialog for making a Github issue with details on the crash. Also if you say the tree view package crashes, you should point that issue to https://github.com/atom/tree-view.

**Comment by Irthen** [comment]
Hey,

I just played a little bit around with your package and the atom core/atom core package. Sorry, this issue is not related to your package because the colors of the tree view are gone, too - even I had disabled/uninstalled your package.

Wishing you a good Sunday afternoon,
Cheers.
