### ISSUE TITLE
Regex filter

### ISSUE THREAD

**Issue by Fmancino** [mrodalgaard/language-log#38]
Hey! I think your plugin is really nice, great job!
I just wander, is it possible to add a regex button to the filter? i think it would make it way more usable by allowing to filter several words at once!

**Comment by Fmancino** [comment]
I am a idiot, realized now that it is on by default... could still be useful to make it look more like other Atom search menus and have a button to toggle regex, but it is by no mean a necessity! Otherwise could be good to tell in the readme that regexes are supported by default.

**Comment by mrodalgaard** [comment]
Thank you for the feedback. I have included this information in the documentation.
