### ISSUE TITLE
softwrap not supported

### ISSUE THREAD

**Issue by lixhunter** [mrodalgaard/language-log#6]
Currently if you have soft-wrap active and set the language to "language-log", lines that exceeds the window are not wrapped.

**Comment by mrodalgaard** [comment]
I set this as default because I was under the impression most users do not want wrapping in log files. I was apparently wrong :smiley:. You can still set this either with the `Editor: Toggle Soft Wrap` command or through Settings -> Packages -> Language Log.

```coffee
'.source.log':
  'editor':
    'softWrap': false
```

**Comment by lixhunter** [comment]
Great, that worked fine. Very nice.
Didn't mind the settings of a single package.
