### ISSUE TITLE
configure file formats

### ISSUE THREAD

**Issue by apptoix** [mrodalgaard/language-log#7]
Hi,
This package is quite useful to view logs.
It would be very useful if it would be possible define which file formats are logs, 
specially because many times .txt files aren't logs, and don't require the filter bar nor require the syntax highlight.

Thanks

**Comment by mrodalgaard** [comment]
Thank you @apptoix. Next release will have some major improvements on detecting log files using the first line and not blindly marking every txt file starting with numbers as a log file.

If you are missing some other file formats then txt, then they need to be added as well. Top of [log.cson](https://github.com/mrodalgaard/language-log/blob/master/grammars/log.cson) shows the current.

**Comment by apptoix** [comment]
Looks great! 
Thanks!
