### ISSUE TITLE
jboss log - WARN not recognized

### ISSUE THREAD

**Issue by ilsaul** [mrodalgaard/language-log#8]
Hi,
i open a server.log and recognized everything except WARN.

example:
18:35:44,633 WARN  [org.springframework.beans.factory.support.DisposableBeanAdapter] (ServerService Thread Pool -- 104) Invocation of destroy method 'close' failed on bean with name 'sqlSession': java.lang.UnsupportedOperationException: Manual close is not allowed over a Spring managed SqlSession

thanks
Saul

**Comment by mrodalgaard** [comment]
Thank you for the feedback.
